# --- main configuration -------------------------------------------

baseurl		 	    = "https://lightjason.github.io/"
languageCode 	    = "en-us"
title 			    = "LightJason"
theme 			    = "lightjason"

[params]
	name 		    = "LightJason"
	description     = "A Lightwire Multi-Agent System"
	listpages		= ["blogpost", "tutorial", "publication"]

[params.sidebar]
	logo 		    = ""

[[params.footer.links]]
	name = "AgentSpeak(L) Repository"
	url  = "https://github.com/LightJason/AgentSpeak"

# ----------------------------------------------------------------------	 


# --- main navigation menu ---------------------------------------------

[[menu.main]]
	Name 			= "Blogpost"
  	URL 			= "/blogpost"
  	weight 			= 0

[[menu.main]]
	Name 			= "Framework"
  	URL			    = "/framework"
  	weight 			= 10

[[menu.main]]
	Name 			= "Tutorial"
  	URL				= "/tutorial"
  	weight 			= 20

[[menu.main]]
	Name 			= "Publication"
  	URL				= "/publication"
  	weight 			= 30	  

[[menu.main]]
	Name 			= "About"
  	URL			    = "/about"
  	weight 			= 40

[[menu.main]]
	Name 			= "Contact"
  	URL 			= "/contact"
  	weight 			= 1000	

# ----------------------------------------------------------------------
