# --- main configuration -------------------------------------------
# see http://www.emoji-cheat-sheet.com/

baseurl		 	       : "https://lightjason.github.io/"
metadataformat		   : "yaml"
ignoreFiles            : [ "\\.graffle$", "\\.sh$", "\\.config" ]
defaultContentLanguage : "en-GB"
theme 			       : "lightjason"
title                  : "LightJason"
enableEmoji            : true
enableRobotsTXT        : true
googleAnalytics		   : "UA-89676576-1"


taxonomies:
    news        	   : "news"


params:
    description        : "Concurrent BDI multi-agent system"
    metadescription    : "LightJason is an artificial intelligence BDI multi-agent framework for adding AI with optimization and fuzzy-logical concepts to existing software-architecture"
    keywords           : "AI, BDI, Agent, Multi-Agent System, Concurrency, Java, Development, Artificial Intelligence, Software, Psychology, Sociology, Simulation"
    contact            : "info@lightjason.org"
    license            : "https://creativecommons.org/licenses/by-sa/4.0/"
    nonexistingdate    : "2017-01-01T12:00:00+01:00"
    date_format        : "2006-01-02"
    bingverify         : "2EB13C5538E9973D8DFC39C6A455DEFE"
    googleverify       : "sVNU1mmaPgvbzlig03vdNtqHYnJNzvbdQYLCWqvtxRU"
    twitter            : "LightJasonAI"
    gitter             :
        user           : "LightJason"
        defaultroom    : "Lobby"

    icon:
        icon           : "images/favicon.png"
        logo           : "images/logo.png"
        type           : "image/png"

    domain:
        protocol       : "http://"
        name           : "lightjason.org"

    person:
        -
            name:
                family : "Aschermann"
                given  : "Malte"
            image      : "http://meclab.in.tu-clausthal.de/images/people/malte_aschermann.png"
            email      : "malte@lightjason.org"
            work       : ["Modelling", "Testing", "Scenario Design", "Teaching / Documentation"]
        -
            name:
                family : "Dennisen"
                given  : "Sophie"
            image  : "http://meclab.in.tu-clausthal.de/images/people/sdennisen.jpg"
            email  : "sophie@lightjason.org"
            work   : ["Modelling", "Testing / Usage", "Scenario Design", "Teaching / Documentation"]
            links:
                -
                    name  : "Xing"
                    image : "https://www.xing.com/img/buttons/9_de_btn.gif"
                    url   : "http://xing.to/sdennisen"
                -
                    name  : "LinkedIn"
                    image : "https://static.licdn.com/scds/common/u/img/webpromo/btn_liprofile_blue_80x15_de_DE.png?locale="
                    url   : "http://www.linkedin.com/in/sdennisen"  
        -
            name:
                family : "Kraus"
                given  : "Philipp"
            image      : "http://www.gravatar.com/avatar/2de3ae533823dae934d3b45b239f797c"
            email      : "philipp@lightjason.org"
            work       : ["Architect", "Developer", "Tutorials", "Webmaster (Admin-C)"]
            links:
                -
                    name  : "Xing"
                    image : "https://www.xing.com/img/buttons/9_de_btn.gif"
                    url   : "http://xing.to/philippkraus"
                -
                    name  : "LinkedIn"
                    image : "https://static.licdn.com/scds/common/u/img/webpromo/btn_liprofile_blue_80x15_de_DE.png?locale="
                    url   : "http://www.linkedin.com/in/philipp-kraus"

    footer:
        links:
            -
                name   : "AgentSpeak(L++)"
                url    : "https://github.com/LightJason/AgentSpeak"

            -
                name   : "Research Gate"
                url    : "https://www.researchgate.net/project/LightJason"    


    socialmedia:
        -
            name       : "github"
            url        : "https://github.com/LightJason"
            weight     : 10
        -
            name	   : "docker"
            url		   : "https://hub.docker.com/u/lightjason"
            weight	   : 30            
        -
            name	   : "twitter"
            url		   : "http://twitter.com/LightJasonAI"
            weight	   : 30
        -
            name       : "vimeo"
            url        : "https://vimeo.com/lightjason"
            weight	   : 40


    menu:
        -
            name 	   : "News"
            url 	   : "/news/"
            weight 	   : 0
            sublink:
                url    : "/news/index.xml"
                name   : "RSS"
        -
            name 	   : "Publications"
            url		   : "/publications/"
            weight 	   : 10
        -
            name 	   : "Framework"
            url		   : "/framework/"
            weight 	   : 20
        -
            name 	   : "Knowledge Base"
            url		   : "/knowledgebase/"
            weight 	   : 30
        -
            name 	   : "Tutorials"
            url		   : "/tutorials/"
            weight 	   : 40
            sublink:
                url    : "/tutorials/wizard"
                name   : "Wizard"
        -
            name 	   : "About"
            url		   : "/about/"
            weight 	   : 500
        -
            name 	   : "Contact"
            url 	   : "/contact/"
            weight 	   : 1000
        -
            name       : "Credits"
            url        : "/credits/"
            weight     : 10000

# ----------------------------------------------------------------------
