# https://github.com/yoshiharuyamashita/blackburn/tree/master/layouts
# https://gohugo.io/templates/terms/



# --- main configuration -------------------------------------------

baseurl		 	    = "https://lightjason.github.io/"
metadataformat		= "yaml"
languageCode 	    = "en-us"
theme 			    = "lightjason"
# see http://www.emoji-cheat-sheet.com/
enableEmoji         = true

# ----------------------------------------------------------------------



# --- main site configuration ------------------------------------------

[taxonomies]
	blogbost        = "blogposts"

[params]
	logo 		    = ""
	name 		    = "LightJason"
	description     = "A Lightwire Multi-Agent System"
	contact         = "info [at] lightjason.org"
	listpages		= ["blogpost", "tutorial", "publication"]

[[params.footer.links]]
	name = "Project Repositories"
	url  = "https://github.com/LightJason"

[[params.footer.links]]
	name = "AgentSpeak(L++) Repository"
	url  = "https://github.com/LightJason/AgentSpeak"

# ----------------------------------------------------------------------	 



# --- main navigation menu ---------------------------------------------

[[menu.main]]
	Name 			= "Blogpost"
  	URL 			= "/blogpost"
  	weight 			= 0

[[menu.main]]
	Name 			= "Framework"
  	URL			    = "/framework"
  	weight 			= 10

[[menu.main]]
	Name 			= "Tutorial"
  	URL				= "/tutorial"
  	weight 			= 20

[[menu.main]]
	Name 			= "Publication"
  	URL				= "/publication"
  	weight 			= 30	  

[[menu.main]]
	Name 			= "About"
  	URL			    = "/about"
  	weight 			= 40

[[menu.main]]
	Name 			= "Contact"
  	URL 			= "/contact"
  	weight 			= 1000	

# ----------------------------------------------------------------------
