# --- main configuration -------------------------------------------
# see http://www.emoji-cheat-sheet.com/

baseurl		 	    = "https://lightjason.github.io/"
metadataformat		= "yaml"
languageCode 	    = "en-us"
theme 			    = "lightjason"
enableEmoji         = true

# ----------------------------------------------------------------------



# --- main site configuration ------------------------------------------

[taxonomies]
	news        	= "news"

[params]
	logo 		    = ""
	name 		    = "LightJason"
	description     = "BDI Multi-Agent System"
	contact         = "info [at] lightjason.org"
	listpages		= ["news", "tutorial", "publication"]

[[params.footer.links]]
	name = "Project Repositories"
	url  = "https://github.com/LightJason"

[[params.footer.links]]
	name = "AgentSpeak(L++) Repository"
	url  = "https://github.com/LightJason/AgentSpeak"

[[params.footer.links]]
	name = "REST-API Repository"
	url  = "https://github.com/LightJason/REST"	

# ----------------------------------------------------------------------	 



# --- main navigation menu ---------------------------------------------

[[params.menu]]
	name 			= "News"
  	url 			= "/news/"
  	weight 			= 0

[[params.menu]]
	name 			= "Framework"
  	url			    = "/framework/"
  	weight 			= 10

[[params.menu]]
	name 			= "Tutorial"
  	url				= "/tutorial/"
  	weight 			= 20

[[params.menu]]
	name 			= "Publication"
  	url				= "/publication/"
  	weight 			= 30	  

[[params.menu]]
	name 			= "About"
  	url			    = "/about/"
  	weight 			= 40

[[params.menu]]
	name 			= "Contact"
  	url 			= "/contact/"
  	weight 			= 1000	

# ----------------------------------------------------------------------
