# --- main configuration -------------------------------------------
# see http://www.emoji-cheat-sheet.com/

baseurl		 	       : "https://lightjason.github.io/"
metadataformat		   : "yaml"
defaultContentLanguage : "en-us"
theme 			       : "lightjason"
title                  : "lightjason.org"
enableEmoji            : true
googleAnalytics		   : "UA-89676576-1"


taxonomies:
    news        	   : "news"


params:
    logo 		       : ""
    name 		       : "LightJason"
    description        : "BDI Multi-Agent System"
    contact            : "info [at] lightjason.org"

    footer:
        links:
            -
                name   : "Project Repositories"
                url    : "https://github.com/LightJason"
            -
                name   : "AgentSpeak(L++) Repository"
                url    : "https://github.com/LightJason/AgentSpeak"
            -
                name   : "REST-API Repository"
                url    : "https://github.com/LightJason/REST"


    menu:
        -
            name 	   : "News"
            url 	   : "/news/"
            weight 	   : 0
        -
            name 	   : "Publication"
            url		   : "/publication/"
            weight 	   : 10            
        -
            name 	   : "Framework"
            url		   : "/framework/"
            weight 	   : 20
        -
            name 	   : "Tutorial"
            url		   : "/tutorial/"
            weight 	   : 30
        -
            name 	   : "About"
            url		   : "/about/"
            weight 	   : 500
        -
            name 	   : "Contact"
            url 	   : "/contact/"
            weight 	   : 1000

# ----------------------------------------------------------------------
